# Simple workflow for deploying static content to GitHub Pages
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["production"]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
jobs:
   
  publish-website:
    name: Publish to the production website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: release
      - name: Push to release branch  
        run: |
          git remote add upstream git@github.com:samhotep/codespaces-actions-playground.git
          git push --force upstream HEAD:release
